### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by njan-creative** [zuenko/ALRF#2]
Latest PyTorch error.. below

Traceback (most recent call last):
  File "MobileNet_CIFAR_LowRankShit_Impl.py", line 129, in <module>
    standard_solver.train()
  File "MobileNet_CIFAR_LowRankShit_Impl.py", line 73, in train
    self.evaluate(epoch_i)
  File "MobileNet_CIFAR_LowRankShit_Impl.py", line 103, in evaluate
    acc1, acc5 = accuracy(logits.cpu(), labels.cpu(), topk=(1, 5))
  File "D:\projects\LowRank\code\ALRF\utils.py", line 76, in accuracy
    correct_k = correct[:k].view(-1).float().sum(0, keepdim=True)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by zuenko** [comment]
#3
